---
- name: add yum repositories
  yum_repository: name="{{ item.key }}"
   description="{{ item.value.description }}"
   file="{{ item.key }}"
   baseurl="{{ item.value.url }}"
   gpgcheck=no
   enabled=yes
  with_dict: "{{ service.zookeeper.repositories }}"
 
- name: install/upgrade prerequisites
  package: name={{ item }} state=present update_cache=yes
  with_items: "{{ service.zookeeper.prerequisites | default([]) }}"