---

# Latest stable version by default
zookeeper_version: "{{ version | default('3.4.11') }}"

apache:
  zookeeper:
  
  # Name of the managed service
      name: "zookeeper"
      
  # Version of the service
      version: "{{ zookeeper_version }}"
                  
  # Base/working directory for pixel tracker
      home: "/opt/zookeeper-3.4.11"
                          
  # Processes and files owner
      owner: "root"
                                  
  # Service settings
      daemon: "zookeeper"
                                          
  # Location of the log files
      logs: /var/log/zookeeper
                                                  
  # Zookeeper options, see official documentation
      options:
        # The number of milliseconds of each tick
          tickTime: 2000
                                                                      
        # The number of ticks that the initial
        # synchronization phase can take
          initLimit: 10
          
        # The number of ticks that can pass tt-ssp
        # sending a request and getting an acknowledgement
          syncLimit: 5
                                                                                                          
        # the directory where the snapshot is stored.
        # do not use /tmp for storage, /tmp here is just
        # example sakes.
          dataDir: /var/lib/zookeeper
                                                                                                                                  
        # the port at which the clients will connect
          clientPort: 2181
                                                                                                                                              
        # the maximum number of client connections.
        # maxClientCnxns: 60
                                                                                                                                                          
        # Be sure to read the maintenance section of the
        # administrator guide before turning on autopurge.
        # autopurge:
        #  # The number of snapshots to retain in dataDir
        #  snapRetainCount: 3
        #  # Purge task interval in hours. Set to "0" to disable auto purge feature
        #  purgeInterval: 1
                                                                                                                                                                                                    
        # A list of hosts in zookeeper cluster
      cluster: []
                                                                                                                                                                                                            
      providers:
           tar:
            # A set of declarations for Zookeeper repositories
            repositories:
            zookeeper:
              url: "http://apache-mirror.rbc.ru/pub/apache/zookeeper/zookeeper-{{ zookeeper_version }}"
