---

  service:
   zookeeper:
    repositories:
     zookeeper:
       url: "http://{{repo.user}}:{{repo.password}}@traineeship-repository.dev.thumbtack.net:8081/nexus/content/repositories/{{repo.name}}/"
       description: "traineeship-repository"

    prerequisites:
      - java-1.8.0-openjdk

    packages:
#      - zookeeper-{{ zookeeper.version }}*
      - zookeeper*
